# Generated by Django 4.2 on 2023-05-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('comments', models.TextField(max_length=250)),
                ('URL', models.URLField()),
                ('status', models.CharField(choices=[('I3', 'Interview3'), ('WA', 'Will Apply'), ('I2', 'Interview2'), ('I4', 'Interview4'), ('I1', 'Interview1'), ('R', 'Rejected'), ('A', 'Applied'), ('OA', 'Online Assessment')], max_length=2)),
            ],
        ),
    ]
