# Generated by Django 4.2 on 2023-05-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savemeapp', '0002_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('WA', 'Will Apply'), ('OA', 'Online Assessment'), ('R', 'Rejected'), ('I3', 'Interview3'), ('A', 'Applied'), ('I1', 'Interview1'), ('I4', 'Interview4'), ('I2', 'Interview2')], max_length=2),
        ),
    ]
