# Generated by Django 4.2 on 2023-05-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savemeapp', '0003_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('I1', 'Interview1'), ('WA', 'Will Apply'), ('R', 'Rejected'), ('I3', 'Interview3'), ('A', 'Applied'), ('I4', 'Interview4'), ('OA', 'Online Assessment'), ('I2', 'Interview2')], max_length=2),
        ),
    ]
