# Generated by Django 4.2 on 2023-05-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savemeapp', '0004_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('I3', 'Interview3'), ('I4', 'Interview4'), ('R', 'Rejected'), ('WA', 'Will Apply'), ('I2', 'Interview2'), ('OA', 'Online Assessment'), ('I1', 'Interview1'), ('A', 'Applied')], max_length=2),
        ),
    ]
